---
x-nautobot: &nautobot
  image: "networktocode/nautobot:v0.0.1"
  depends_on:
    - postgres
    - redis
  env_file:
    - dev.env
  tty: true

x-nautobot-worker: 

version: "3"
services:
  nautobot1:
    <<: *nautobot
    ports:
      - "8011:8001"
  nautobot2:
    <<: *nautobot
    ports:
      - "8012:8001"
  worker1:
    <<: *nautobot-worker
    ports:
      - ""

  postgres:
    image: postgres:10
    env_file:
      - dev.env
    volumes:
      - pgdata_nautobot:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file:
      - dev.env
volumes:
  pgdata_nautobot: